name: Adbay
favicon: null
layout_spectrum: 0.25954615091905
typography_spectrum: 0.7016946184448898
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.0660456360783428
  lightness: 0.9452911065891385
  saturation: 0.1560706002637744
  rhythmicContrast: 0.07393779745325446
purpose: []
